<?xml version="1.0"?>
<package format="3">
  <name>bxi_orbslam3_ros2</name>
  <version>0.1.0</version>
  <description>ELF3 RGB-D-Inertial ORB-SLAM3 ROS 2 adapter.</description>
  <maintainer email="3223759606@qq.com">hwc</maintainer>
  <license>GPL-3.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>cv_bridge</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>rtabmap_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
